# Generated by Django 5.1.3 on 2024-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=255)),
                ('screen_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('a', 'Available'), ('u', 'Unavailable')], max_length=1)),
                ('made_in', models.CharField(max_length=255)),
            ],
        ),
    ]
