# Generated by Django 5.1.3 on 2024-11-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
