# Generated by Django 5.1.3 on 2024-11-27 21:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0002_alter_mobile_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
